In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect(
    "../database/sustainability.db"
)

print("Connected Successfully")

Connected Successfully

In [3]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

tables = pd.read_sql_query(query, conn)

tables

              name
0        Countries
1  sqlite_sequence
2  RenewableEnergy
3     CO2Emissions

In [4]:
query1 = """
SELECT
    c.country_name,
    ROUND(
        AVG(r.renewables_share_energy),
        2
    ) AS avg_renewable_energy

FROM Countries c

JOIN RenewableEnergy r
ON c.country_id = r.country_id

GROUP BY c.country_name

ORDER BY avg_renewable_energy DESC;
"""

result1 = pd.read_sql_query(
    query1,
    conn
)

result1

    country_name  avg_renewable_energy
0          Spain                 14.44
1          Italy                 12.40
2        Germany                 11.04
3         France                  8.97
4          China                  8.90
5          India                  6.92
6  United States                  6.62

In [5]:
query2 = """
SELECT
    c.country_name,
    ROUND(
        AVG(e.co2),
        2
    ) AS avg_co2

FROM Countries c

JOIN CO2Emissions e
ON c.country_id = e.country_id

GROUP BY c.country_name

ORDER BY avg_co2 DESC;
"""

result2 = pd.read_sql_query(
    query2,
    conn
)

result2

    country_name  avg_co2
0          China  8365.68
1  United States  5555.27
2          India  1872.22
3        Germany   801.60
4          Italy   409.80
5         France   358.82
6          Spain   288.54

In [6]:
query3 = """
SELECT
    c.country_name,
    r.year,
    r.renewables_share_energy,
    e.co2

FROM Countries c

JOIN RenewableEnergy r
ON c.country_id = r.country_id

JOIN CO2Emissions e
ON c.country_id = e.country_id
AND r.year = e.year

ORDER BY
    c.country_name,
    r.year;
"""

result3 = pd.read_sql_query(
    query3,
    conn
)

result3.head(20)

   country_name  year  renewables_share_energy        co2
0         China  2000                 5.335688   3643.810
1         China  2001                 6.251407   3724.114
2         China  2002                 5.921867   4098.181
3         China  2003                 5.001339   4835.251
4         China  2004                 5.289435   5210.961
5         China  2005                 5.238741   5881.991
6         China  2006                 5.266756   6486.185
7         China  2007                 5.406529   6974.663
8         China  2008                 6.872421   7492.404
9         China  2009                 6.559855   7881.491
10        China  2010                 7.194704   8610.048
11        China  2011                 6.696764   9520.153
12        China  2012                 8.067560   9767.311
13        China  2013                 8.473828   9942.371
14        China  2014                 9.689675   9976.027
15        China  2015                10.277580   9858.040
16        China  2016                11.113145   9748.175
17        China  2017                11.665639  10000.014
18        China  2018                12.224382  10346.790
19        China  2019                12.785955  10713.515